init dev
Firesieht/MIPT-Python-Laba pull request #1
Opened 2024-11-22 23:17 UTC by Firesieht

2024-12-01 21:29 UTC, dKosarevsky requested changes
добавь фамилию в ридми

2024-12-01 21:29 UTC, dKosarevsky commented
и номер группы

2024-12-03 08:50 UTC, Firesieht commented
Добавил Фамилию и номер группы

2024-12-07 11:54 UTC, dKosarevsky approved these changes
8

2024-12-07 11:54 UTC, merged